### ISSUE TITLE
Remove redundant packages from requirements.txt

### ISSUE THREAD

**Issue by abhipaiangle** [wncc/Hello-FOSS-Dev#3]
Remove redundant packages from requirements.txt. Test it on your local machine by setting up a virtual environment and resolve the issue

**Comment by sauntheninja2** [comment]
So I tested the app in a virtual environment and it works with only three packages installed 1.Requests 2.Flask and 3. Flask-SocketIO

**Comment by sanidhyaanand** [comment]
I would like to work on this

**Comment by abhipaiangle** [comment]
@sanidhyaanand  Yeah Sure! Make sure you use virtual env for testing. Send in the PR once you're done
